"use strict";

var path = require('path');
var config = module.exports = {};

config.context = __dirname;

config.resolve = {
  extensions: [" ", ".jsx", ".js"]
};
// Specify your entries, I store all my webpack managed JavaScript in
// app/webpack, as per my earlier requirements.
config.entry = {
  App: [
    './scripts/app.jsx'
  ]
};

// 'output' specifies the filepath for saving the bundled output generated by
// wepback.
// It is an object with options, and you can interpolate the name of the entry
// file using '[name]' in the filename.
// You will want to add the bundled filename to your '.gitignore'.p/assets/javascripts/entries/foobar.js.
config.output = {
  path: path.join(__dirname, "./app/assets/javascripts/"),
  publicPath: 'assets/',
  filename: "[name].js"
}

// Use bab el-loader for our *.js files.
config.module = {
  loaders: [
    {
      // Pattern to match only files with the '.js' or '.jsx' extension.
      // This tells the loader to only run for those files.
      test: /\.jsx?$/,
      // @see https://github.com/shama/es6-loader
      // It was installed with 'npm install es6-loader --save' and transpiles
      // es6 to es5.
      loader: 'es6-loader',
      exclude: /node_modules/,
      loader: "babel-loader",
      query: {
        presets: [ "react", "es2015", "stage-0" ]
      }
    }
  ],
}
